### ISSUE TITLE
Visual developing HTML view

### ISSUE THREAD

**Issue by goandylok** [totaljs/framework#255] opened 2015-03-15 15:52 UTC
Hi Peter Širka,

I am looking for some ways to edit my HTML views with advanced visual editor like WebStorm.  Then,  I turned model tags into angularjs, but found that images and other public resources are routed to /view/  that caused 404 without {image()} tag. How could I do this? Or is nodejs app were not designed to be edited visually?
Thank you.

By the way, totalJs is the best framework I have ever seen, I love it since I saw it.

**Comment by petersirka** [comment] 2015-03-15 20:48
Hi @goandylok,
I don't see the light at the end of the tunnel :1234:  ... The problem: you want to edit views with some designer app. The problem is in routing of static files because the designer app doesn't know where are static files (because they are in `public` directory).

So only way is change the configuration of designer app and set the directory for static files.

PS: many thanks for your compliments, I appreciate it.

**Comment by petersirka** [comment] 2015-03-19 06:47
I have closed this issue.

**Closed by petersirka** 2015-03-19 06:47 UTC
